FROM toke/mosquitto

WORKDIR /app
RUN apt-get update && apt-get -y install python3-pip 

COPY . /app
# COPY mosquitto.conf /mqtt/config
RUN pip3 install -r  /app/requirements.txt
EXPOSE $PORT
CMD python3 -u publisher.py